# Generated by Django 3.2.4 on 2021-06-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
