# Generated by Django 3.2.7 on 2021-10-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='property_type',
        ),
    ]
