# Generated by Django 3.2.7 on 2021-10-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_registers_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer'), ('staff', 'staff')], default='customer', max_length=30),
        ),
    ]
