# Generated by Django 3.2.7 on 2021-10-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_complaints_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='title',
        ),
    ]
