# Generated by Django 3.2.7 on 2021-10-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_requiremt_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiremt',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='requiremt',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requiremt',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requiremt',
            name='status',
            field=models.CharField(choices=[('finished', 'finished'), ('notfinished', 'notfinished')], default='notfinished', max_length=30),
        ),
    ]
