# Generated by Django 3.2.7 on 2021-10-18 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_amount'),
        ('blog', '0010_auto_20211018_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiremt',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
    ]
