# Generated by Django 3.2.7 on 2021-10-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_requiremt_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiremt',
            name='payment',
        ),
    ]
