# Generated by Django 3.2.7 on 2021-10-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_requiremt_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiremt',
            name='work',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
