# Generated by Django 3.1.4 on 2021-10-22 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20211022_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiremt',
            name='square_feet',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
