# Generated by Django 3.1.4 on 2021-10-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_requiremt_square_feet'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
