# Generated by Django 3.1.4 on 2021-10-23 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0022_auto_20211022_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='is_online',
        ),
        migrations.AlterField(
            model_name='register',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
