# Generated by Django 3.2.6 on 2021-12-06 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_pricetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiremt',
            name='percentage',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
